### ISSUE TITLE
Kobuki connection refused

### ISSUE THREAD

**Issue by abhijay9** [JdeRobot/colab-gsoc2017-SepehrMohaimanian#4]
After 2 days of setup and battling with configuration issues I finally ran `python Laser2DAgent.py --load_weights weights/laser2D_baseline --render` to reproduce the results as shown in [jderobot.org/Deep_Reinforcement_Learning_in_Robotics](https://jderobot.org/Deep_Reinforcement_Learning_in_Robotics). Though at the step where I am making the environment:

    env = gym.make(env_name) # where env_name is 'jde-gazebo-kobuki-laser2D-v0'

it gave me the following error:

	loading Ice.Config file /home/abhijay/git_clones/colab-gsoc2017-SepehrMohaimanian/src/drivers/gazeboserver/plugins/turtlebot/cfg/gym_kobuki_conf.cfg
	Receiving kobuki.Laser LaserData from ICE interfaces
	kobuki.Laser: connection refused
	Publishing Motors with ICE interfaces
	kobuki.Motors.maxW not provided, the default value is used: 0.5
	kobuki.Motors.maxV not provided, the default value is used: 5
	kobuki.Motors: connection refused
	Publishing GazeboAction with ICE interfaces
	kobuki.Reset: connection refused
	--------------------------------
	None
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 171, in make
	    return registry.make(id, **kwargs)
	  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 123, in make
	    env = spec.make(**kwargs)
	  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 87, in make
	    env = cls(**_kwargs)
	  File "/home/abhijay/git_clones/colab-gsoc2017-SepehrMohaimanian/src/tools/openAI_gym_env/gym-gazebo/jde_gym_gazebo/envs/kobuki_laser2D_env.py", line 36, in __init__
	    self.observation_dims = [ len(laser.values), len(laser.values)]
	AttributeError: 'NoneType' object has no attribute 'values'

It would be great if you can help figure out the issue. Thank you

**Comment by abhijay9** [comment]
Fortunately, I tried the docker mentioned by [erlerobot gym gazebo](https://github.com/erlerobot/gym-gazebo) and it works beautifully.  

Here are the links: 
https://github.com/JdeRobot/gym-gazebo/blob/master/INSTALL.md#ubuntu-1604  
https://github.com/erlerobot/gym-gazebo/blob/master/INSTALL.md
